//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaTileStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LedgerSupplier
    {
        public int Id { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Description { get; set; }
        public string Balance { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
